language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

env:
  - SYMFONY_ENV=test_travis

before_install:
  - sudo mkdir -p /var/cache/janus-ssp/janus && sudo chmod -R 777 /var/cache/janus-ssp
  - sudo mkdir -p /var/log/janus-ssp/janus && sudo chmod -R 777 /var/log/janus-ssp
  - mysql -e 'create database janus_test;'

before_script: composer install -n

script: phpunit -c app

notifications:
  email:
    - janus-ssp-dev@googlegroups.com
